--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13/09/2018 19:47:50
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE restaurante;

--
-- Drop table `compra`
--
DROP TABLE IF EXISTS compra;

--
-- Drop table `proveedor`
--
DROP TABLE IF EXISTS proveedor;

--
-- Drop table `detalleventa`
--
DROP TABLE IF EXISTS detalleventa;

--
-- Drop table `plato`
--
DROP TABLE IF EXISTS plato;

--
-- Drop table `recetainsumo`
--
DROP TABLE IF EXISTS recetainsumo;

--
-- Drop table `receta`
--
DROP TABLE IF EXISTS receta;

--
-- Drop table `factura`
--
DROP TABLE IF EXISTS factura;

--
-- Drop table `venta`
--
DROP TABLE IF EXISTS venta;

--
-- Drop table `cliente`
--
DROP TABLE IF EXISTS cliente;

--
-- Drop table `empleado`
--
DROP TABLE IF EXISTS empleado;

--
-- Drop table `insumo`
--
DROP TABLE IF EXISTS insumo;

--
-- Drop table `detallecompra`
--
DROP TABLE IF EXISTS detallecompra;

--
-- Set default database
--
USE restaurante;

--
-- Create table `detallecompra`
--
CREATE TABLE detallecompra (
  idInsumo int(11) NOT NULL,
  idCompra int(11) NOT NULL,
  cantidad int(11) DEFAULT NULL,
  PRIMARY KEY (idInsumo, idCompra)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `FK_detallecompra_idCompra` on table `detallecompra`
--
ALTER TABLE detallecompra
ADD INDEX FK_detallecompra_idCompra (idCompra);

--
-- Create table `insumo`
--
CREATE TABLE insumo (
  idInsumo int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(255) DEFAULT NULL,
  precio double DEFAULT NULL,
  PRIMARY KEY (idInsumo)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE insumo
ADD CONSTRAINT FK_insumo_detallecompra_idInsumo FOREIGN KEY (idInsumo)
REFERENCES detallecompra (idInsumo) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `empleado`
--
CREATE TABLE empleado (
  idEmpleado int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(255) DEFAULT NULL,
  apellido varchar(255) DEFAULT NULL,
  fechaNaci date DEFAULT NULL,
  telefono int(11) DEFAULT NULL,
  PRIMARY KEY (idEmpleado)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `cliente`
--
CREATE TABLE cliente (
  idCliente int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(255) DEFAULT NULL,
  apellido varchar(255) DEFAULT NULL,
  fechaNaci date DEFAULT NULL,
  telefono int(11) DEFAULT NULL,
  ci int(11) DEFAULT NULL,
  PRIMARY KEY (idCliente)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `venta`
--
CREATE TABLE venta (
  idVenta int(11) NOT NULL AUTO_INCREMENT,
  idCliente int(11) DEFAULT NULL,
  idEmpleado int(11) DEFAULT NULL,
  numeroVenta int(11) DEFAULT NULL,
  PRIMARY KEY (idVenta)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE venta
ADD CONSTRAINT FK_venta_idCliente FOREIGN KEY (idCliente)
REFERENCES cliente (idCliente) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE venta
ADD CONSTRAINT FK_venta_idEmpleado2 FOREIGN KEY (idEmpleado)
REFERENCES empleado (idEmpleado) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `factura`
--
CREATE TABLE factura (
  idVenta int(11) NOT NULL AUTO_INCREMENT,
  precioTot double DEFAULT NULL,
  fecha date DEFAULT NULL,
  PRIMARY KEY (idVenta)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE factura
ADD CONSTRAINT FK_factura_idVenta FOREIGN KEY (idVenta)
REFERENCES venta (idVenta) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `receta`
--
CREATE TABLE receta (
  idReceta int(11) NOT NULL AUTO_INCREMENT,
  descripcion varchar(255) DEFAULT NULL,
  PRIMARY KEY (idReceta)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `recetainsumo`
--
CREATE TABLE recetainsumo (
  idRectaInsumo int(11) NOT NULL AUTO_INCREMENT,
  idReceta int(11) DEFAULT NULL,
  idInsumo int(11) DEFAULT NULL,
  cantidad varchar(255) DEFAULT NULL,
  PRIMARY KEY (idRectaInsumo)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE recetainsumo
ADD CONSTRAINT FK_recetainsumo_idInsumo FOREIGN KEY (idInsumo)
REFERENCES insumo (idInsumo) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE recetainsumo
ADD CONSTRAINT FK_recetainsumo_idReceta FOREIGN KEY (idReceta)
REFERENCES receta (idReceta) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `plato`
--
CREATE TABLE plato (
  idPlato int(11) NOT NULL AUTO_INCREMENT,
  precio double DEFAULT NULL,
  nombre varchar(255) DEFAULT NULL,
  idReceta int(11) DEFAULT NULL,
  PRIMARY KEY (idPlato)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE plato
ADD CONSTRAINT FK_plato_idReceta FOREIGN KEY (idReceta)
REFERENCES receta (idReceta) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `detalleventa`
--
CREATE TABLE detalleventa (
  idDetalleVenta int(11) NOT NULL AUTO_INCREMENT,
  idVenta int(11) DEFAULT NULL,
  idPlato int(11) DEFAULT NULL,
  cantidad int(11) DEFAULT NULL,
  PRIMARY KEY (idDetalleVenta)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE detalleventa
ADD CONSTRAINT FK_detalleventa_idPlato FOREIGN KEY (idPlato)
REFERENCES plato (idPlato) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE detalleventa
ADD CONSTRAINT FK_detalleventa_idVenta FOREIGN KEY (idVenta)
REFERENCES venta (idVenta) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `proveedor`
--
CREATE TABLE proveedor (
  idProveedor int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(255) DEFAULT NULL,
  telefono int(11) DEFAULT NULL,
  PRIMARY KEY (idProveedor)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `compra`
--
CREATE TABLE compra (
  idCompra int(11) NOT NULL AUTO_INCREMENT,
  fecha date DEFAULT NULL,
  idProveedor int(11) DEFAULT NULL,
  PRIMARY KEY (idCompra)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE compra
ADD CONSTRAINT FK_compra_detallecompra_idCompra FOREIGN KEY (idCompra)
REFERENCES detallecompra (idCompra) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE compra
ADD CONSTRAINT FK_compra_idProveedor FOREIGN KEY (idProveedor)
REFERENCES proveedor (idProveedor) ON DELETE CASCADE ON UPDATE CASCADE;

-- 
-- Dumping data for table detallecompra
--
-- Table restaurante.detallecompra does not contain any data (it is empty)

-- 
-- Dumping data for table empleado
--
-- Table restaurante.empleado does not contain any data (it is empty)

-- 
-- Dumping data for table cliente
--
-- Table restaurante.cliente does not contain any data (it is empty)

-- 
-- Dumping data for table receta
--
-- Table restaurante.receta does not contain any data (it is empty)

-- 
-- Dumping data for table insumo
--
-- Table restaurante.insumo does not contain any data (it is empty)

-- 
-- Dumping data for table venta
--
-- Table restaurante.venta does not contain any data (it is empty)

-- 
-- Dumping data for table plato
--
-- Table restaurante.plato does not contain any data (it is empty)

-- 
-- Dumping data for table proveedor
--
-- Table restaurante.proveedor does not contain any data (it is empty)

-- 
-- Dumping data for table recetainsumo
--
-- Table restaurante.recetainsumo does not contain any data (it is empty)

-- 
-- Dumping data for table factura
--
-- Table restaurante.factura does not contain any data (it is empty)

-- 
-- Dumping data for table detalleventa
--
-- Table restaurante.detalleventa does not contain any data (it is empty)

-- 
-- Dumping data for table compra
--
-- Table restaurante.compra does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;